name: 'Lock Threads'

on:
  schedule:
    - cron: '50 6 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  discussions: write

concurrency:
  group: lock-threads

jobs:
  lock-threads:
    if: github.repository_owner == 'jertel'
    runs-on: ubuntu-latest
    steps:
      - uses: jertel/lock-threads@main
        with:
          include-discussion-currently-open: true
          discussion-inactive-days: 90
          issue-inactive-days: 365
          pr-inactive-days: 365
